### ISSUE TITLE
代码的运行细节

### ISSUE THREAD

**Issue by TitanSneaker** [qingyue2014/MoE4DST#1]
您好，代码运行顺序是怎样的？方便提供代码的运行sh文件吗？

**Comment by qingyue2014** [comment]
先进入cluster文件夹运行run_cluster.sh 再在main文件中运行run.sh。 上述sh文件已上传～

**Comment by Dxyhy** [comment]
您好，选用的几个T5模型有没有HuggingFace的下载链接
